[workspace]
resolver = "2"
members = [
    "main",
    "libraries/*",
    "plugins/*",
    "xtask",
]

[workspace.package]
version = "0.0.1-alpha.3"
edition = "2021"
authors = ["きりしまあおい nakamurakensuke5@gmail.com"]
repository = "https://github.com/FlandollScarlet495/rust-app-sample"
license = "MIT"

[workspace.dependencies]
core = { path = "libraries/core" }
debug_util = { path = "libraries/debug_util" }
common_build = { path = "plugins/common_build" }
