[package]
name = "plugin_sample"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
path = "src/plugin_sample.rs"

[dependencies]
core = { workspace = true }
debug_util = { workspace = true }

[build-dependencies]
common_build = { workspace = true }
